"""HTML templates for the static knowledge-base site."""

from __future__ import annotations

import json
from html import escape
from typing import Any
from urllib.parse import quote


def h(value: Any) -> str:
    return escape(str(value or ""), quote=True)


def format_date(value: str) -> str:
    if not value:
        return ""
    return value.split("T", 1)[0]


def score_text(value: Any) -> str:
    try:
        return f"{float(value):.2f}"
    except (TypeError, ValueError):
        return "0.00"


def query_link(page: str, key: str, value: str) -> str:
    return f"{page}?{key}={quote(value)}"


def tag_html(tags: list[str], *, link_base: str | None = None) -> str:
    parts: list[str] = []
    for tag in tags:
        if link_base:
            href = query_link(link_base, "tag", tag)
            parts.append(f'<a class="tag" href="{h(href)}">{h(tag)}</a>')
        else:
            parts.append(f'<span class="tag">{h(tag)}</span>')
    return "".join(parts)


def meta_row(article: dict[str, Any], *, link_base: str | None = None) -> str:
    source = str(article.get("source") or "")
    source_html = f'<span class="source-pill">{h(source)}</span>'
    if link_base and source:
        source_html = f'<a class="source-pill" href="{h(query_link(link_base, "source", source))}">{h(source)}</a>'
    return (
        '<div class="meta-row">'
        f'<span class="score">{score_text(article.get("relevance_score"))}</span>'
        f"{source_html}"
        f'<span>{h(format_date(article.get("organized_at", "")))}</span>'
        "</div>"
    )


def article_card(article: dict[str, Any], *, compact: bool = False) -> str:
    summary = "" if compact else f"<p>{h(article.get('summary'))}</p>"
    return f"""
<article class="article-card" data-article-card="{h(article['id'])}">
  <a class="article-card-main" href="{h(article['href'])}">
    {meta_row(article)}
    <h3>{h(article.get('title'))}</h3>
    {summary}
  </a>
  <div class="meta-row tag-row">{tag_html(article.get('tags', [])[:4], link_base='library.html')}</div>
</article>
"""


def mini_card(article: dict[str, Any]) -> str:
    return f"""
<a class="mini-card" href="{h(article['href'])}">
  {meta_row(article)}
  <h3>{h(article.get('title'))}</h3>
</a>
"""


def latest_item(article: dict[str, Any]) -> str:
    return f"""
<article class="latest-item">
  <div>{meta_row(article)}</div>
  <a href="{h(article['href'])}"><h3>{h(article.get('title'))}</h3></a>
  <p>{h(article.get('summary'))}</p>
</article>
"""


def option_list(values: list[str], label: str) -> str:
    options = [f'<option value="all">{h(label)}</option>']
    options.extend(f'<option value="{h(value)}">{h(value)}</option>' for value in values)
    return "\n".join(options)


def base_page(*, title: str, body: str, stylesheet: str = "assets/styles.css", body_class: str = "") -> str:
    class_attr = f' class="{h(body_class)}"' if body_class else ""
    return f"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{h(title)}</title>
  <link rel="stylesheet" href="{h(stylesheet)}">
</head>
<body{class_attr}>
  <div class="site-shell">
    {body}
  </div>
</body>
</html>
"""


def site_header(*, active: str, prefix: str = "") -> str:
    home_active = ' aria-current="page"' if active == "home" else ""
    library_active = ' aria-current="page"' if active == "library" else ""
    return f"""
<header class="site-header">
  <a class="site-mark" href="{h(prefix)}index.html">MyGK_DB</a>
  <nav class="site-nav" aria-label="Primary">
    <a href="{h(prefix)}index.html"{home_active}>首页</a>
    <a href="{h(prefix)}library.html"{library_active}>资料库</a>
  </nav>
</header>
"""


def site_footer() -> str:
    return '<footer class="site-footer">Generated by MyGK_DB static site builder.</footer>'


def index_page(
    *,
    articles: list[dict[str, Any]],
    tags: list[str],
    sources: list[str],
    last_updated: str,
) -> str:
    featured = articles[0] if articles else None
    side = articles[1:4]
    latest = articles[4:10] if len(articles) > 4 else articles[1:7]
    top_tags = tags[:8]

    featured_html = ""
    if featured:
        featured_html = f"""
<section class="feature-grid" aria-label="精选文章">
  <a class="feature-card" href="{h(featured['href'])}">
    <span class="eyebrow">本期精选</span>
    {meta_row(featured)}
    <h2>{h(featured.get('title'))}</h2>
    <p>{h(featured.get('summary'))}</p>
  </a>
  <div class="feature-side">
    {''.join(mini_card(article) for article in side)}
  </div>
</section>
"""

    latest_html = "".join(latest_item(article) for article in latest)
    tag_links = tag_html(top_tags, link_base="library.html")
    source_links = "".join(
        f'<a class="quiet-link" href="{h(query_link("library.html", "source", source))}">{h(source)}</a>'
        for source in sources[:4]
    )

    body = f"""
{site_header(active="home")}
<main>
  <section class="hero">
    <div class="hero-copy">
      <span class="eyebrow">AI / LLM / Agent 技术情报</span>
      <h1>一座为长期阅读整理的 AI 知识库</h1>
      <p>从 GitHub、RSS 等来源沉淀高质量条目。首页只保留少量精选，完整搜索、标签和来源筛选放在资料库页面。</p>
      <div class="hero-actions">
        <a class="button" href="library.html">进入资料库</a>
        <a class="button secondary" href="#latest">查看最新</a>
      </div>
    </div>
    <dl class="summary-panel">
      <div><dt>文章</dt><dd>{len(articles)}</dd></div>
      <div><dt>标签</dt><dd>{len(tags)}</dd></div>
      <div><dt>来源</dt><dd>{len(sources)}</dd></div>
      <div><dt>更新</dt><dd>{h(format_date(last_updated))}</dd></div>
    </dl>
  </section>
  <section class="page-section">
    {featured_html}
  </section>
  <section class="page-section topic-entry" aria-label="快速入口">
    <div>
      <span class="eyebrow">快速进入</span>
      <h2>按主题或来源继续浏览</h2>
    </div>
    <div class="topic-groups">
      <div class="tag-row">{tag_links}</div>
      <div class="source-row">{source_links}</div>
    </div>
  </section>
  <section class="page-section" id="latest">
    <div class="section-title">
      <div>
        <span class="eyebrow">最新整理</span>
        <h2>最近 6 篇</h2>
      </div>
      <a class="text-link" href="library.html">查看全部 {len(articles)} 篇</a>
    </div>
    <div class="latest-list">{latest_html}</div>
  </section>
</main>
{site_footer()}
"""
    return base_page(title="MyGK_DB Knowledge", body=body, body_class="home-page")


def library_page(
    *,
    articles: list[dict[str, Any]],
    tags: list[str],
    sources: list[str],
    last_updated: str,
) -> str:
    cards = "\n".join(article_card(article) for article in articles)
    body = f"""
{site_header(active="library")}
<main class="library-page">
  <header class="library-hero">
    <span class="eyebrow">资料库</span>
    <h1>搜索、筛选和回看全部条目</h1>
    <p>这里承载完整检索能力。首页保持安静，所有标签、来源、分数和排序操作都在这里完成。</p>
    <div class="library-meta">
      <span>{len(articles)} 篇文章</span>
      <span>{len(tags)} 个标签</span>
      <span>{len(sources)} 个来源</span>
      <span>更新于 {h(format_date(last_updated))}</span>
    </div>
  </header>
  <section class="library-tools" aria-label="文章筛选">
    <label class="search-field">
      <span>搜索</span>
      <input type="search" data-search placeholder="标题、摘要、标签或来源">
    </label>
    <label>
      <span>标签</span>
      <select data-tag-filter>{option_list(tags, '全部标签')}</select>
    </label>
    <label>
      <span>来源</span>
      <select data-source-filter>{option_list(sources, '全部来源')}</select>
    </label>
    <label>
      <span>分数</span>
      <select data-score-filter>
        <option value="all">全部分数</option>
        <option value="high">0.80 以上</option>
        <option value="medium">0.60 - 0.79</option>
        <option value="low">0.60 以下</option>
      </select>
    </label>
    <label>
      <span>排序</span>
      <select data-sort>
        <option value="latest">最新优先</option>
        <option value="score">高分优先</option>
        <option value="title">标题排序</option>
      </select>
    </label>
  </section>
  <section class="library-results">
    <div class="section-title">
      <div>
        <span class="eyebrow">结果</span>
        <h2>文章列表</h2>
      </div>
      <span data-count-label>{len(articles)} 篇</span>
    </div>
    <div class="empty-state" data-empty-state>没有匹配的文章。</div>
    <div class="article-grid">{cards}</div>
  </section>
</main>
{site_footer()}
<script src="search-data.js"></script>
<script src="assets/app.js"></script>
"""
    return base_page(title="资料库 - MyGK_DB", body=body, body_class="library")


def article_page(
    *,
    article: dict[str, Any],
    content_html: str,
    toc_html: str,
    related: list[dict[str, Any]],
    previous_article: dict[str, Any] | None,
    next_article: dict[str, Any] | None,
    has_body: bool,
) -> str:
    source_url = article.get("content_source_url") or article.get("url") or "#"
    fetched = article.get("content_fetched_at")
    status = "" if has_body else '<div class="content-state">正文尚未入库。当前展示的是分析摘要；后续抓取原文后将自动渲染为长文阅读页。</div>'
    fetched_html = f'<div><span>原文入库</span><strong>{h(format_date(fetched))}</strong></div>' if fetched else ""
    related_html = "".join(mini_card(item) for item in related)
    previous_html = f'<a href="{h(previous_article["href"])}">上一篇：{h(previous_article.get("title"))}</a>' if previous_article else "<span></span>"
    next_html = f'<a href="{h(next_article["href"])}">下一篇：{h(next_article.get("title"))}</a>' if next_article else "<span></span>"
    body = f"""
{site_header(active="", prefix="../")}
<nav class="article-topbar" aria-label="Article">
  <a href="../library.html">返回资料库</a>
  <a href="{h(source_url)}" target="_blank" rel="noopener noreferrer">打开原文</a>
</nav>
<main class="reader">
  <header class="reader-header">
    <div class="reader-kicker">
      <span class="score">{score_text(article.get('relevance_score'))}</span>
      <span class="source-pill">{h(article.get('source'))}</span>
      {tag_html(article.get('tags', [])[:5], link_base='../library.html')}
    </div>
    <h1>{h(article.get('title'))}</h1>
    <p class="summary-lede">{h(article.get('summary'))}</p>
    <div class="reader-meta">
      <div><span>采集</span><strong>{h(format_date(article.get('collected_at', '')))}</strong></div>
      <div><span>分析</span><strong>{h(format_date(article.get('analyzed_at', '')))}</strong></div>
      <div><span>归档</span><strong>{h(format_date(article.get('organized_at', '')))}</strong></div>
      {fetched_html}
    </div>
    {status}
  </header>
  {toc_html}
  <article class="prose">{content_html}</article>
  <section class="related">
    <div class="section-title"><div><span class="eyebrow">相关阅读</span><h2>同标签条目</h2></div><span>{len(related)} 篇</span></div>
    <div class="related-grid">{related_html}</div>
  </section>
  <nav class="article-nav">{previous_html}{next_html}</nav>
</main>
{site_footer()}
"""
    return base_page(title=f"{article.get('title')} - MyGK_DB", body=body, stylesheet="../assets/styles.css", body_class="article")


def search_data_script(articles: list[dict[str, Any]]) -> str:
    payload = [
        {
            "id": article.get("id", ""),
            "title": article.get("title", ""),
            "summary": article.get("summary", ""),
            "source": article.get("source", ""),
            "tags": article.get("tags", []),
            "relevance_score": article.get("relevance_score", 0),
            "organized_at": article.get("organized_at", ""),
            "href": article.get("href", ""),
        }
        for article in articles
    ]
    return "window.MYGK_SEARCH_DATA = " + json.dumps(payload, ensure_ascii=False) + ";"
